### ISSUE TITLE
transfomer被翻译成变形金刚或者变压器

### ISSUE THREAD

**Issue by peilibo** [hellotransformers/Natural_Language_Processing_with_Transformers#1]
1.GPT和BERT为各种NLP基准设定了新的技术状态，并迎来了变压器的时代。
2.你将在这些文字中发现的信息的广度和深度将是令人震惊的。 它涵
盖了从变形金刚架构本身，到变形金刚库和围绕它的整个生态系统的所有内容。

建议这些不用翻译，直接保留transformer

**Comment by znsoftm** [comment]
感谢。你可以直接修改pr.

**Comment by znsoftm** [comment]
具体在哪 章？

**Comment by znsoftm** [comment]
已经全部重新处理完成。
